### ISSUE TITLE
Anaconda virtualEnv not showing after activation

### ISSUE THREAD

**Issue by vkulikov** [wellic/bash_tools#1]
now:
> 505: 11:49:44 vkulikov@vkulikov-ubuntu /home/vkulikov/PycharmProjects/project1 [master *% u= origin/master]
> $ source activate condaenv3
> 
> 506: 11:50:30 vkulikov@vkulikov-ubuntu /home/vkulikov/PycharmProjects/project1 [master *% u= origin/master]

expected:

> 505: 11:49:44 vkulikov@vkulikov-ubuntu /home/vkulikov/PycharmProjects/project1 [master *% u= origin/master]
> $ source activate condaenv3
> 
> [condaenv3] 506: 11:50:30 vkulikov@vkulikov-ubuntu /home/vkulikov/PycharmProjects/project1 [master *% u= origin/master]
>

**Comment by wellic** [comment]
Improved
